/*
You have access to the following three tables:

`ads_metadata` (ad metadata table)
- `campaign_id`: unique campaign ID
- `campaign_name`: campaign name
- `budget`: budget

`ad_events` (ad event log table)
- High-frequency log table; each row is one event.
- `event_id`, `timestamp`, `campaign_id`
- `event_type`: event type ('impression' or 'click')
- `cost`: cost generated by this event

`conversions` (conversion table)
- `conversion_id`, `timestamp`, `campaign_id`
- `revenue`: revenue from the purchase

Task
Write a query to generate a per-campaign report for the last 30 days, including:
- Campaign Name
- Total Spend
- Total Revenue
- ROAS (Total Revenue / Total Spend)
- Conversion Rate (Total Conversions / Total Clicks)

Constraints
- Include only campaigns with impressions >= 1,000.
- Exclude campaigns with clicks = 0 (to avoid divide-by-zero errors).
*/

WITH daily_stats AS (
    SELECT
        campaign_id,
        SUM(CASE WHEN event_type = 'impression' THEN 1 ELSE 0 END) AS impressions,
        SUM(CASE WHEN event_type = 'click' THEN 1 ELSE 0 END) AS clicks,
        SUM(cost) AS total_spend
    FROM ad_events
    WHERE timestamp >= CURRENT_DATE - INTERVAL '30 days'
    GROUP BY 1
),
daily_conversions AS (
    SELECT
        campaign_id,
        SUM(revenue) AS total_revenue,
        COUNT(conversion_id) AS total_conversions
    FROM conversions
    WHERE timestamp >= CURRENT_DATE - INTERVAL '30 days'
    GROUP BY 1
)
SELECT
    m.campaign_name,
    s.total_spend,
    COALESCE(c.total_revenue, 0) AS total_revenue,
    ROUND(COALESCE(c.total_revenue, 0) / NULLIF(s.total_spend, 0), 2) AS roas,
    ROUND(CAST(COALESCE(c.total_conversions, 0) AS FLOAT) / NULLIF(s.clicks, 0), 4) AS conversion_rate
FROM ads_metadata m
JOIN daily_stats s
  ON m.campaign_id = s.campaign_id
LEFT JOIN daily_conversions c
  ON m.campaign_id = c.campaign_id
WHERE s.impressions >= 1000
  AND s.clicks > 0;
